name: pylops_t22
channels:
  - defaults
  - conda-forge
  - numba
  - pytorch
dependencies:
  - python>=3.6.4
  - pip
  - numpy>=1.15.0
  - scipy>=1.4.0
  - matplotlib
  - pylops
  - ipython
  - jupyter
  - pytorch=1.8.1
  - torchvision
  - tqdm
  - sympy
  - pip:
    - torchsummary
    - pylops-gpu
    - pyproximal