name: pylops_t22
channels:
  - defaults
  - conda-forge
  - numba
dependencies:
  - python>=3.6.4
  - numpy>=1.15.0
  - scipy>=1.4.0
  - matplotlib
  - pylops==1.18.0
  - pywavelets
  - ipython
  - jupyter
  - pip:
    - pympler
    - pyproximal
    - scooby
    - segyio